apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: cloud-app
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-service.cloud-app.svc.cluster.local:9090
        access: proxy
        isDefault: true
        editable: false
