server:
  port: 8080

spring:
  application:
    name: cloud-app

cloud:
  aws:
    endpoint: ${LOCALSTACK_URL:http://localhost:4566}
    region: ${AWS_REGION:us-east-1}
    access-key: ${AWS_ACCESS_KEY_ID:test}
    secret-key: ${AWS_SECRET_ACCESS_KEY:test}
    s3-bucket: ${S3_BUCKET_NAME:documents-bucket}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
